### ISSUE TITLE
SemanticDB creates the wrong symbol in certain cases involving variadic argument lists

### ISSUE THREAD

**Issue by mberndt123** [scalameta/scalameta#1239] opened 2018-02-01 00:01 UTC
Hey guys,

I've tried to write a scalafix rule to move the order of some type parameters around (for the fastparse library). Here's the code:

https://github.com/mberndt123/fastparse-new-order/tree/912492da6b76f4b8056e079dd81f2e4e95edc294

As you can see, the rule itself is quite straight-forward:
```scala
    val ParserExtract = SymbolMatcher.exact(Symbol("_root_.fastparse.core.Parser#"))
    ctx.tree.collect {
      case Type.Apply(ParserExtract(_), a :: b :: c :: Nil) =>
        ctx.replaceTree(a, b.syntax) +
          ctx.replaceTree(b, c.syntax) +
          ctx.replaceTree(c, a.syntax)
    }.fold(Patch.empty)(_ + _)
```
iow, every time the `Parser` type constructor is applied to some type parameters, the first type parameter should be moved to the end. However the test case fails, because this
```scala
case class Either[T, Elem, Repr](ps: Parser[T, Elem, Repr]*) extends Parser[T, Elem, Repr]
```
isn't rewritten to this
```scala
case class Either[T, Elem, Repr](ps: Parser[Elem, Repr, T]*) extends Parser[Elem, Repr, T]
```
but to this
```scala
case class Either[T, Elem, Repr](ps: Parser[T, Elem, Repr]*) extends Parser[Elem, Repr, T]
```
To me it looks as if there's a problem with the SemanticdbIndex. If I replace `ParserExtract(_)` with `tpe` in the case clause and add a `println(index.symbol(tpe))`, I get the following output:
```
Some(_root_.scala.`<repeated>`#)
Some(_root_.fastparse.core.Parser#)
Some(_root_.fastparse.core.Parser#)
```
Somehow SemanticDB seems to be confused about which type constructor is applied to the three type parameters.

**Comment by olafurpg** [comment] 2018-05-28 17:35
Thanks for reporting! This is a duplicate of #1432

**Closed by olafurpg** 2018-05-28 17:35 UTC
Labels: Metac
