### ISSUE TITLE
AST get changed after `ast.syntax.parse` due to elimination of semicolon

### ISSUE THREAD

**Issue by Atry** [scalameta/scalameta#1013] opened 2017-07-11 03:50 UTC
``` scala
Welcome to the Ammonite Repl 1.0.0
(Scala 2.12.2 Java 1.8.0_131)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ import scala.meta._ 
import scala.meta._
@ q"System.nanoTime; { val foo = 2; println(foo) }" 
res1: Term.Block = Term.Block(
  List(
    Term.Select(Term.Name("System"), Term.Name("nanoTime")),
    Term.Block(List(Defn.Val(List(), List(Pat.Var.Term(Term.Name("foo"))), None, Lit.Int(2)), Term.Apply(Term.Name("println"), List(Term.Name("foo")))))
  )
)
@ res1.syntax.parse[Term] 
res2: Parsed[Term] = Success(
  Term.Block(
    List(
      Term.Apply(
        Term.Select(Term.Name("System"), Term.Name("nanoTime")),
        List(Term.Block(List(Defn.Val(List(), List(Pat.Var.Term(Term.Name("foo"))), None, Lit.Int(2)), Term.Apply(Term.Name("println"), List(Term.Name("foo"))))))
      )
    )
  )
)
```

**Comment by olafurpg** [comment] 2017-07-11 07:55
Thank you for reporting! This appears to be a duplicate of  the top issue in https://github.com/scalameta/scalameta/issues/567#issue-195539795 The pretty-printer should emit a blank line when the following line starts with a curly brace, this is a case where scala's attempt to be whitespace insignificant backfires.

**Comment by xeno-by** [comment] 2017-07-11 16:12
@Atry, thanks for reporting! @olafurpg, thanks for the analysis! I'm closing this issue in favor of #567, since it indeed looks like a duplicate.

Issues like that increase my personal priority of https://github.com/scalameta/scalameta/issues/994. Our current implementation of the prettyprinter is so brittle that fixing this issue (which should be really simple) is really annoying.

**Closed by xeno-by** 2017-07-11 16:12 UTC
Labels: Prettyprinting
