### ISSUE TITLE
Inconsistent tokens results for Term.ApplyInfix.args

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#1444] opened 2018-03-20 08:58 UTC
```scala
def structure(source: String): String = 
  source.parse[Stat].get.asInstanceOf[Term.ApplyInfix].args.head.tokens.structure 

// This is what I get
structure("a op (f)") == "Tokens(( [5..6), f [6..7), ) [7..8))"

// This is what I expect
structure("a op (f)") == "Tokens(f [6..7))"

// With multiple args I get what I expect
structure("a op (f, g)") == "Tokens(f [6..7))"
```

**Comment by olafurpg** [comment] 2018-03-20 09:29
Duplicate of https://github.com/scalameta/scalameta/issues/1083, in scalafix we workaround the problem with 
```scala
      val syntax = name.syntax
      // workaround for https://github.com/scalameta/scalameta/issues/1083
      val pos =
        if (syntax.startsWith("(") &&
          syntax.endsWith(")") &&
          syntax != name.value)
          Position.Range(name.pos.input, name.pos.start + 1, name.pos.end - 1)
        else name.pos
```
would be good to fix this at the root

**Closed by olafurpg** 2018-03-20 09:29 UTC
Labels: Parsing
