### ISSUE TITLE
make Input sealed

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#882] opened 2017-05-22 21:15 UTC
This is yet another idea wrt tightening the types of our core data structures. 

Back in the day, we unsealed `Input` because `Tokens` was subclassing it (for the reasons that are long irrelevant). Afterwards, we decoupled one from another, but forgot to put the `sealed` modifier back. This should be done now.

**Comment by olafurpg** [comment] 2017-07-03 11:30
I'm in favor of this change. I was surprised to find out that `Input` is not sealed. I think the only Input outside the file is `VirtualInput` https://github.com/scalameta/scalameta/blob/f7463f78227e092b5dab0a05667733b0a2b23952/scalameta/trees/shared/src/main/scala/scala/meta/internal/inputs/VirtualInput.scala

**Comment by olafurpg** [comment] 2017-07-06 09:10
There seems to be a valid reason for keeping `VirtualInput`, see https://github.com/scalameta/scalameta/blob/bb4bf3d8e604e2b5bada6f2455670bb0db6ffba1/scalameta/scalameta/shared/src/test/scala/scala/meta/tests/trees/TokensSuite.scala#L30 What should we do @xeno-by ? I personally find `ScalametaTokenizer.megaCache` absolutely terrifying (I think it's the cause of https://github.com/scalameta/scalameta/issues/778) and would love to get rid of it somehow.

**Comment by xeno-by** [comment] 2017-07-07 02:42
Why can't we replace `VirtualInput` by `LabeledString`/`VirtualFile` in this code? 

On the topic of `megaCache`, I think that it exists only because we needed reasonable performance of `Tree.tokens` on synthetic trees. Once we no longer synthesize tokens, this will become moot anyway, right?

**Comment by olafurpg** [comment] 2017-07-07 06:34
> Why can't we replace VirtualInput by LabeledString/VirtualFile in this code?

What should be the label for VirtualInput?

> Once we no longer synthesize tokens, this will become moot anyway, right?

How do we avoid synthetic tokens for synthetic trees?

**Comment by olafurpg** [comment] 2017-07-07 09:18
I'm not sure what to do here. I don't think I have the necessary context around megacache to confidently refactor VirtualInput. I will leave this ticket to you @xeno-by

**Comment by olafurpg** [comment] 2017-07-12 16:07
Fixed in d5d08f3

**Closed by olafurpg** 2017-07-12 16:07 UTC
Labels: Breaking, Trees
