### ISSUE TITLE
Problem with quasiquote for "Application"

### ISSUE THREAD

**Issue by johannegger** [scalameta/scalameta#301] opened 2015-11-03 15:55 UTC
the description quasiquote for Application has 3 '.'s ```q"$expr(...$aexprssnel)"```
however  ```"foo(1)".parse[Stat].collect{ case q"$expr(...$aexprssnel)" => aexprssnel }``` does not work.
it works using only 2 '.'s 
but ```"foo(1,2)(2)".parse[Stat] match { case q"$expr(..$aexprssnel)" => aexprssnel }``` returns only the last argument list ```List(2)```. 
To obtain the first list as well one can do ```"foo(1,2)(2)".parse[Stat] match { case q"$expr(..$aexprssnel)(..$bexprssnel)" => (aexprssnel,bexprssnel) }``` but that's i guess not the desired behavior.

**Comment by xeno-by** [comment] 2015-11-24 13:07
This is the most important of the quasiquote bugs scheduled for 0.0.5.

**Comment by xeno-by** [comment] 2016-05-26 13:53
Duplicate of #277

**Closed** 2016-05-26 13:53 UTC
Labels: Quasiquotes
