### ISSUE TITLE
Output of for comprehensions

### ISSUE THREAD

**Issue by etorreborre** [scalameta/scalameta#1051] opened 2017-07-26 07:28 UTC
Given the following macro annotation
```scala
class identity extends StaticAnnotation {

  inline def apply(defn: Any): Any = meta {
    defn
  }

}
```
and this code using it
```scala
@identity
case class K() {

  def test: List[Int] = {
    for {
      a <- List(1)
      x = 1
    } yield a + x
  }

}
```

I expect the exact same code to be present in the rewritten class but when I compile I get
```scala
[error] <macro>:5: missing parameter type for expanded function ((x$1: <error>) => x$1: @scala.unchecked)
[error]   }).map((_: @scala.unchecked()) match {
[error]           ^
[error] <macro>:6: constructor cannot be instantiated to expected type;
[error]  found   : (T1, T2)
[error]  required: <error> => <error> @unchecked
[error]     case (a, x) =>
```
This is using scalameta `1.8.0` and scala `2.12.2` (same thing for `1.9.0-834-25e73d6d`).

**Comment by fommil** [comment] 2017-07-26 07:54
I think this is a dupe of one I encountered recently.

**Comment by etorreborre** [comment] 2017-07-27 06:46
I seems to have similar issue with pattern matched values:
```scala
for {
  x <- List(1)
  (y, z) <- List((2, 3))
} yield x + y + z
```

**Comment by xeno-by** [comment] 2017-09-01 17:50
Resubmitted as https://github.com/scalameta/paradise/issues/223.

**Closed** 2017-09-01 17:52 UTC
