### ISSUE TITLE
Prettyprint regression of ApplyInfix on Term.Placeholder

### ISSUE THREAD

**Issue by RCMartins** [scalameta/scalameta#1839] opened 2019-03-03 00:18 UTC
Issue:
```scala
val tree = q"list.reduce(_.foo + _.bar)"

println(tree.syntax == "list.reduce(_.foo + _.bar)") // false
println(tree.syntax == "list.reduce(_.foo + (_.bar))") // true (this doesn't compile)
```

This was working correctly on v4.1.4, so it's a regression.

**Comment by olafurpg** [comment] 2019-03-08 12:43
@RCMartins is this possibly a duplicate of #1843? It's not clear how to best represent in the AST the differences between those two programs.

**Comment by RCMartins** [comment] 2019-03-09 10:42
@olafurpg You're right, when I opened this issue I wasn't aware of #1843 ambiguity problem yet.
Maybe we should close this one?

**Comment by olafurpg** [comment] 2019-03-09 11:49
Sounds good.

**Closed by olafurpg** 2019-03-09 11:49 UTC
