### ISSUE TITLE
Error when opening console from sbt

### ISSUE THREAD

**Issue by fdietze** [scalameta/scalameta#927] opened 2017-06-07 06:55 UTC
build.sbt:
```scala
scalaVersion := "2.12.2"

addCompilerPlugin("org.scalameta" % "paradise" % "3.0.0-M9" cross CrossVersion.full)
```
(also applies for scala 2.11.11)

```bash
$ sbt console
```
error:
```
Welcome to Scala 2.12.2 (OpenJDK 64-Bit Server VM, Java 1.8.0_131).
Type in expressions for evaluation. Or try :help.

scala> [init] error: error while loading Object, Missing dependency 'object scala in compiler mirror', required by /nix/store/3ifbp95mh61nrryf95xkbb95xq32azc3-openjdk-8u131b11/lib/openjdk/jre/lib/rt.jar(java/lang/Object.class)
[error] (run-main-0) java.lang.reflect.InvocationTargetException
```

**Comment by olafurpg** [comment] 2017-06-07 06:57
Thank you for reporting! This is a duplicate of https://github.com/scalameta/paradise/issues/10 and has a documented workaround here http://scalameta.org/tutorial/#Setupbuild

**Comment by fdietze** [comment] 2017-06-07 06:58
That was quick! Thank you!

**Closed by olafurpg** 2017-06-07 06:57 UTC
