### ISSUE TITLE
No way to ..$tparams if empty

### ISSUE THREAD

**Issue by blast-hardcheese** [scalameta/scalameta#602] opened 2017-01-27 02:47 UTC
It makes sense why there's no `...$tparams`, but it would be helpful if `..$tparams` collapsed down to `Nil` if empty.

Error:
```
[error] when verifying targs.!=(null).&&(targs.nonEmpty)
[error] found that targs.nonEmpty is false
[error] where targs = List()
[error]         at org.scalameta.invariants.InvariantFailedException$.raise(Exceptions.scala:15)
[error]         at scala.meta.Term$ApplyType$.internal$26(Trees.scala:63)
[error]         at scala.meta.Term$ApplyType$.apply(Trees.scala:63)
```

Workaround:
```
    q"""
    def ${opTerm}(...${paramsList :+ implicitParams}): EitherT[Future, ClientError, $responseTypeRef] = {
      ServiceClient.$opTerm(httpClient)($urlWithParams)
    }
    """.copy(tparams = typeParams)
```

**Comment by xeno-by** [comment] 2017-01-29 21:02
This is a duplicate of https://github.com/scalameta/scalameta/issues/519. When writing my PhD thesis, I realized that `...$tparams` is actually very useful, so I created a note for myself to implement it.

By the way, @blast-hardcheese, would you be up for hacking up this functionality? If you'd like, I could provide some initial pointers.

**Closed by xeno-by** 2017-01-29 21:02 UTC

**Comment by blast-hardcheese** [comment] 2017-01-30 03:51
@xeno-by: I could give it a shot -- I feel comfortable as a consumer, but I haven't touched the parser. Where would you start?

**Comment by blast-hardcheese** [comment] 2017-01-30 04:52
A naive first attempt would be:
```diff
diff --git a/scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala b/scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
index 7d560428..e0ac2530 100644
--- a/scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
+++ b/scalameta/scalameta/src/test/scala/scala/meta/tests/quasiquotes/SuccessSuite.scala
@@ -140,6 +140,13 @@ class SuccessSuite extends FunSuite {
     assert(q"type $name[$a] = $b".show[Structure] === "Defn.Type(Nil, Type.Name(\"List\"), Seq(Type.Param(Seq(Mod.Covariant()), Type.Name(\"A\"), Nil, Type.Bounds(None, None), Nil, Nil)), Type.Name(\"B\"))")
   }
 
+  test("I'm lost! q\"foo[..${Seq.empty[Type]}]\"") {
+    val app = q"foo[..${Seq.empty[Type]}]"
+    val q"foo[..$tparams]" = app
+    assert(app.show[Structure] === "Term.ApplyType(Term.Name(\"foo\"), Nil)")
+    assert(tparams.isEmpty)
+  }
+
   test("1 val q\"def x = ${body: Int}\"") {
     val q"def x = ${body: Int}" = q"def x = 42"
     assert(body === 42)
diff --git a/scalameta/trees/src/main/scala/scala/meta/Trees.scala b/scalameta/trees/src/main/scala/scala/meta/Trees.scala
index f8a1711a..7e507bda 100644
--- a/scalameta/trees/src/main/scala/scala/meta/Trees.scala
+++ b/scalameta/trees/src/main/scala/scala/meta/Trees.scala
@@ -60,7 +60,7 @@ object Term {
     require(parts.length == args.length + 1)
   }
   @ast class Apply(fun: Term, args: Seq[Arg]) extends Term with Ctor.Call
-  @ast class ApplyType(fun: Term, targs: Seq[Type] @nonEmpty) extends Term with Ctor.Call
+  @ast class ApplyType(fun: Term, targs: Seq[Type]) extends Term with Ctor.Call // Collapse ApplyType(_, Nil)?
   @ast class ApplyInfix(lhs: Term, op: Name, targs: Seq[Type], args: Seq[Arg]) extends Term
   @ast class ApplyUnary(op: Name, arg: Term) extends Term.Ref {
     require(op.isUnaryOp)
```
This round-trips, but
```
  test("I'm lost! q\"foo[..$tparams]\" = q\"foo\"") {
    val q"foo[..$tparams]" = q"foo"
    assert(tparams.isEmpty)
  }
```
fails. I'm going to stop here for now, but I'll follow the breadcrumbs in
```
[info] - I'm lost! q"foo[..$tparams]" = q"foo" *** FAILED ***
[info]   scala.MatchError: foo (of class scala.meta.Term$Name$TermNameImpl)
[info]   at scala.meta.tests.quasiquotes.SuccessSuite$$anonfun$23.apply(SuccessSuite.scala:151)
[info]   at scala.meta.tests.quasiquotes.SuccessSuite$$anonfun$23.apply(SuccessSuite.scala:150)
[info]   at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
[info]   at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
[info]   at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
[info]   ...
```
at my next opportunity.

**Comment by xeno-by** [comment] 2017-02-04 01:09
@blast-hardcheese I think it'd be useful to support `...$` instead of giving `..$Nil` special semantics just for type paramteres.

Personally I'd start with modifying the parser to allow `...$` in places where one can write type parameters (currently, only `..$` is allowed there).

Afterwards, I'd go and change the logic in `Liftables.scala` that handles special cases in quasiquoting syntax: https://github.com/scalameta/scalameta/blob/c1376e60883f2c309f57a55e46b48f864a3be99b/scalameta/common/src/main/scala/scala/meta/internal/ast/Liftables.scala#L89. This part may be really tough, so please let me know if you need assistance there.
