### ISSUE TITLE
NoClassDefFoundError: javax/xml/bind/DatatypeConverter for Java 10

### ISSUE THREAD

**Issue by avdv** [scalameta/scalameta#1796] opened 2018-10-22 16:27 UTC
Trying to use the semanticdb-scalac plugin
```scala
addCompilerPlugin("org.scalameta" % "semanticdb-scalac" % "4.0.0" cross CrossVersion.full)
```
causes the following error when compiling a project with SBT 1.2.6:
```
## Exception when compiling 57 sources to /home/claudio/src/media/target/scala-2.12/classes
 javax/xml/bind/DatatypeConverter
 scala.meta.internal.semanticdb.scalac.InputOps$XtensionGSourceFileInput.toMD5(InputOps.scala:41)
 scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toTextDocument(TextDocumentOps.scala:614)
 scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.saveSemanticdbForCompilationUnit(SemanticdbPipeline.scala:59)
 scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.apply(SemanticdbPipeline.scala:65)
 scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:441)
 scala.tools.nsc.Global$GlobalPhase.run(Global.scala:392)
 scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.run(SemanticdbPipeline.scala:75)
 scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1467)
 scala.tools.nsc.Global$Run.compileUnits(Global.scala:1451)
 scala.tools.nsc.Global$Run.compileSources(Global.scala:1444)
 scala.tools.nsc.Global$Run.compile(Global.scala:1567)
 xsbt.CachedCompiler0.run(CompilerInterface.scala:130)
 xsbt.CachedCompiler0.run(CompilerInterface.scala:105)
 xsbt.CompilerInterface.run(CompilerInterface.scala:31)
 java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 java.base/java.lang.reflect.Method.invoke(Method.java:564)
 sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
 sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:111)
 sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:90)
 sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$3(MixedAnalyzingCompiler.scala:82)
 scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
 sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:133)
 sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:73)
 sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:116)
 sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:307)
 sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:307)
 sbt.internal.inc.Incremental$.doCompile(Incremental.scala:106)
 sbt.internal.inc.Incremental$.$anonfun$compile$4(Incremental.scala:87)
 sbt.internal.inc.IncrementalCommon.recompileClasses(IncrementalCommon.scala:116)
 sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:63)
 sbt.internal.inc.Incremental$.$anonfun$compile$3(Incremental.scala:89)
 sbt.internal.inc.Incremental$.manageClassfiles(Incremental.scala:134)
 sbt.internal.inc.Incremental$.compile(Incremental.scala:80)
 sbt.internal.inc.IncrementalCompile$.apply(Compile.scala:67)
 sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:311)
 sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:269)
 sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:159)
 sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:238)
 sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:69)
 sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:1544)
 sbt.Defaults$.$anonfun$compileIncrementalTask$1(Defaults.scala:1518)
 scala.Function1.$anonfun$compose$1(Function1.scala:44)
 sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
 sbt.std.Transform$$anon$4.work(System.scala:67)
 sbt.Execute.$anonfun$submit$2(Execute.scala:269)
 sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
 sbt.Execute.work(Execute.scala:278)
 sbt.Execute.$anonfun$submit$1(Execute.scala:269)
 sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
 sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
 java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514)
 java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
 java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135)
 java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
 java.base/java.lang.Thread.run(Thread.java:844)
            
 java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
 	at scala.meta.internal.semanticdb.scalac.InputOps$XtensionGSourceFileInput.toMD5(InputOps.scala:41)
 	at scala.meta.internal.semanticdb.scalac.TextDocumentOps$XtensionCompilationUnitDocument.toTextDocument(TextDocumentOps.scala:614)
 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.saveSemanticdbForCompilationUnit(SemanticdbPipeline.scala:59)
 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.apply(SemanticdbPipeline.scala:65)
 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:441)
 	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:392)
 	at scala.meta.internal.semanticdb.scalac.SemanticdbPipeline$SemanticdbTyperComponent$ComputeSemanticdbPhase.run(SemanticdbPipeline.scala:75)
```

According to https://stackoverflow.com/a/43574427/4432837 there are a couple of methods to mitigate this for JDK 9 and 10.

Using the `sbt -J'--add-modules java.xml.bind'` works for JRE > 8, but fails for older JREs.

Adding the jaxb-api and jaxb-runtime dependencies should also work, but no dice trying it thusly:
```
addCompilerPlugin("javax.xml.bind" % "jaxb-api" % "2.3.1")
addCompilerPlugin("org.glassfish.jaxb" % "jaxb-runtime" % "2.3.1")
```

Seems those dependencies do not make it onto the plugins classpath?!

Should these libraries be added to dependencies of the semanticdb-scalac plugin itself?

**Comment by olafurpg** [comment] 2018-10-22 17:50
Thanks for reporting! This is a duplicate of https://github.com/scalameta/scalameta/issues/1779 we can replace `javax/xml/bind/DatatypeConverter` with a basic method to print hex strings from `Array[Byte]`.

**Comment by avdv** [comment] 2018-10-23 06:12
Hi Ólafur,

yes, I saw this ticket, but being specifically about Java 11, I figured this could be a sort of quick win for Java 9/10 until #1779 is worked on.

But you're right, replacing DatatypeConverter calls would be easy to do, as a first step towards #1779.

I could try to create a PR?

**Comment by olafurpg** [comment] 2018-10-23 06:36
Sounds good @avdv I agree this is an easy win as first step towards #1779, a PR would be welcome. We can use this method here https://github.com/scalameta/metals/blob/8ba8ac9c29d4ab51424de9ad1c9a2e86d956a75d/mtags/src/main/scala/scala/meta/internal/mtags/MD5.scala#L16-L27 to replace the usage of `DatatypeConverter` here https://github.com/scalameta/scalameta/blob/d64c7ff22d87d67c7608c65269ed401202a61769/semanticdb/scalac/library/src/main/scala/scala/meta/internal/semanticdb/scalac/InputOps.scala#L41

**Comment by avdv** [comment] 2018-10-23 09:44
I have prepared a PR, comments welcome ;-)

Should I also replace calls in the tests as well? Here: https://github.com/scalameta/scalameta/blob/232d56a457f92582ca2cc1ac5a8f96780a8415f4/tests/jvm/src/test/scala/scala/meta/tests/semanticdb/MD5Suite.scala

**Closed** 2018-10-23 10:17 UTC
