### ISSUE TITLE
Off-by-one parse error

### ISSUE THREAD

**Issue by stuhood** [scalameta/scalameta#778] opened 2017-03-30 23:44 UTC
Parsing the attached file
[Loggers.scala.txt](https://github.com/scalameta/scalameta/files/884082/Loggers.scala.txt) with `1.7.0-485-086c4ac9` results in a stack like the following:
```
Cause: java.lang.ArrayIndexOutOfBoundsException: 2086
java.lang.ArrayIndexOutOfBoundsException: 2086
at scala.meta.internal.parsers.ScalametaParser.<init>(ScalametaParser.scala:168)
at scala.meta.internal.parsers.ScalametaParser$$anon$202.apply(ScalametaParser.scala:3787)
at scalafix.Scalafix$.fix(Scalafix.scala:18)
at scalafix.cli.Cli$.handleFile(Cli.scala:145)
...
```

**Comment by xeno-by** [comment] 2017-03-31 13:36
@olafurpg I downloaded the file and ran the following app:

```scala
import scala.meta._

object Test extends App {
  val f = new java.io.File("Loggers.scala.txt")
  println(f.parse[Source])
}
```

Surprisingly, everything worked correctly. Is there anything special about how scalafix invokes the scala.meta parser?

**Comment by stuhood** [comment] 2017-04-03 21:49
It looks like this is likely related to static caches in scalameta or scalafix. It only occurs on the second run of scalameta/scalafix after edits to a file have made the file shorter.

**Comment by olafurpg** [comment] 2017-04-04 09:06
That sounds likely, I suspect the culprit might be `megaCache` then https://github.com/scalameta/scalameta/blob/5413739ef52e517f5cf876ee87b617ddfa097396/scalameta/tokenizers/jvm/src/main/scala/scala/meta/internal/tokenizers/PlatformTokenizerCache.scala#L15 I've always been sceptical of that one, and I think it may be the cause of errors like https://github.com/scalameta/scalafmt/issues/850

**Comment by xeno-by** [comment] 2017-09-06 00:49
Duplicate of #1068.

**Closed by xeno-by** 2017-09-06 00:49 UTC
Labels: Parsing
