### ISSUE TITLE
StackOverflow in Transformer

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#1352] opened 2018-02-20 15:38 UTC
wget https://raw.githubusercontent.com/apache/kafka/trunk/core/src/main/scala/kafka/server/KafkaConfig.scala

```scala
import scala.meta.transversers.Transformer
object noopTransform extends Transformer {
  override def apply(tree: Tree): Tree = super.apply(tree)
}
import java.nio.file._
val in = new String(Files.readAllBytes(Paths.get("/home/gui/scala-syntax/KafkaConfig.scala"))) 
val code = in.parse[Source].get 
noopTransform(code)
```

**Comment by MasseGuillaume** [comment] 2018-02-20 16:43
```scala
import scala.meta.transversers.Transformer
object noopTransform extends Transformer {
  override def apply(tree: Tree): Tree = super.apply(tree)
}
val deepSelect = (1 to 100).map(x =>".d()").mkString
val input = 
  s"""|object A {
      |  val a = a$deepSelect
      |}""".stripMargin

val code = input.parse[Source].get 
noopTransform(code)
```

This happens on a deep select chain:

`foo.bar().bar().bar().bar().bar().bar().bar().bar().bar() ...`

**Comment by olafurpg** [comment] 2018-05-28 17:27
Duplicate of https://github.com/scalameta/scalameta/issues/1353 This is a known issue, the parser is not stack safe and likely won't be addressed in the near future.

**Closed by olafurpg** 2018-05-28 17:27 UTC
Labels: Trees

**Comment by dieu** [comment] 2021-10-15 19:50
@olafurpg is any workaround available for safe transform?

**Comment by olafurpg** [comment] 2021-10-17 12:25
Increasing the stack size should work
