### ISSUE TITLE
Synthetic trees from quasiquotes should not have tokens

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#1600] opened 2018-06-12 16:39 UTC
for example:

```scala
val tree = q"def f" 

Decl.Def(
  Nil,
  Term.Name("f"),
  Nil,
  Nil,
  Type.Name("Unit") // << synthetic
)

tree.decltpe.tokens.isEmpty

// obtained: false
// expected: true

val tree2 = q"if (p) t" 
Term.If(
  Term.Name("p"),
  Term.Name("t"),
  Lit.Unit()  // << synthetic
)

tree2.decltpe.tokens.isEmpty

// obtained: false
// expected: true
```

**Comment by MasseGuillaume** [comment] 2018-06-12 16:44
this is only limited to quasiquotes:

```scala
val Term.If(_, _, elsep) = "if (p) t".parse[Term].get 
elsep.tokens.isEmpty // true

val Term.If(_, _, elsep2) = "if (p) t else f".parse[Term].get 
elsep2.tokens.isEmpty // false
```

**Comment by olafurpg** [comment] 2018-06-12 19:16
For better or worse, this is how quasiquotes/tokens work. Would it be better if `.tokens` on quasiquotes returns an empty list of tokens?

```scala
q"def foo".tokens.isEmpty // true
```

It has always bugged me that `.tokens`/`.syntax` plays two roles

- re-print syntax from existing source code
- synthesize new syntax when there is no existing source code

Quasiquotes expand at compile-time into tree constructors 
```
@ q"def foo"
res18: Decl.Def = Decl.Def(List(), Term.Name("foo"), List(), List(), Type.Name("Unit"))

@ q"def foo: Unit"
res19: Decl.Def = Decl.Def(List(), Term.Name("foo"), List(), List(), Type.Name("Unit"))
```
There's no API to attribute `Unit` in `q"def foo: Unit` with positions/tokens, quasiquotes don't even have positions.

**Comment by olafurpg** [comment] 2018-06-13 14:27
Closing with "working as intended". The workaround is to test against the `Token.input` which gives you information whether the tree nodes comes from a quasiquote or not.

**Closed by olafurpg** 2018-06-13 14:27 UTC
