### ISSUE TITLE
Retain formatting upon performing unrelated source transformations

### ISSUE THREAD

**Issue by akhileshs** [scalameta/scalameta#399] opened 2016-05-19 17:31 UTC
This issue forms the the first goal of #379.

As discussed over there, if we had, 

``` scala
scala> "{ /* hello */ def foo(bar: Int) = ??? }".parse[Term].get
res0: scala.meta.Term = { /* hello */ def foo(bar: Int) = ??? }

scala> res0.transform { case q"bar" => q"baz" } 
res1: scala.meta.Tree =
{
  def foo(baz: Int) = ???
}
```

The result of the transformation should retain the original source formatting and other relevant details (comments in this case).

**Comment by xeno-by** [comment] 2017-07-05 23:07
I'm closing this as a duplicate of #379.

**Closed by xeno-by** 2017-07-05 23:07 UTC
Labels: Prettyprinting
