### ISSUE TITLE
scaladoc is broken

### ISSUE THREAD

**Issue by fdietze** [scalameta/scalameta#1233] opened 2018-01-26 16:25 UTC
When trying to generate scaladoc for my project, it fails at the following code:

```scala
@derive((id, revision) => Equality)
case class Real(id: UserId, name: String, revision: Int) extends Persisted
```
Error
```
[error] src/main/scala/Graph.scala:24:26: no arguments allowed for nullary constructor derive: ()derive.derive
[error]   @derive((id, revision) => Equality)
[error]                          ^
```

`@derive` comes from the `scalameta` library https://github.com/cornerman/derive ([Derive.scala](https://github.com/cornerman/derive/blob/master/src/main/scala/Derive.scala#L311)).

**Comment by olafurpg** [comment] 2018-01-26 16:34
Thanks for reporting! Closing as duplicate of https://github.com/scalameta/paradise/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+scaladoc Unfortunately, there is no pending fix on the roadmap.

**Closed by olafurpg** 2018-01-26 16:34 UTC

**Comment by fdietze** [comment] 2018-01-26 17:36
Sad. Isn't there a way to ignore code parts to be parsed by scaladoc?
