### ISSUE TITLE
Scalacp includes inaccessible object constructor

### ISSUE THREAD

**Issue by olafurpg** [scalameta/scalameta#1493] opened 2018-04-12 15:34 UTC
The class info type for objects produced by metacp includes the inaccesible object constructor
```
$ metap -proto $(metacp $(coursier fetch org.scala-lang:scala-library:2.12.4)) | grep "declarations:.*Sorting.*init"
        declarations: "scala.util.Sorting.`<init>`()."
```

I expect the constructor to be excluded from the declarations list.
PS. There is no symbol information for `scala.util.Sorting.`<init>`().`

**Comment by lgirault** [comment] 2018-05-26 15:19
I'm trying to solve this one. If I understand correctly the filtering is supposed to happen around the `scala.meta.internal.javacp.asm.MethodSignatureVisitor`. But does the `scala.tools.asm.tree.MethodNode` hold any information about the fact that it is accessible or not ? Is it possible to retrieve such information from the byte code ?

**Comment by olafurpg** [comment] 2018-05-27 07:05
@lgirault cool! This issue is in Scalacp, which uses scalap to parse Scala signatures in classfiles. `javacp` is for extracting signatures from Java signatures.

A good place to start would be 

1. reproduce this bug with an expect test by writing code in https://github.com/scalameta/scalameta/tree/da7b6e8baf146e133402f7428d75e6458414e09b/semanticdb/integration/src/main/scala/example and testing with `testsJVM/testOnly *ExpectSuite -- -z metacp.expect`
2. look here https://github.com/scalameta/scalameta/blob/da7b6e8baf146e133402f7428d75e6458414e09b/semanticdb/metacp/src/main/scala/scala/meta/internal/scalacp/Scalacp.scala#L269

I removed the "Good first contribution" since this ticket is probably harder than I originally anticipated.

**Comment by lgirault** [comment] 2018-05-27 12:49
Cool ! thank you for the tips. Actually I think I'm not clear with the list of cli and what they do. Given the line you gave in the initial description of this issue, I thought that  matacp since its argument is a class jar would extract a semanticdb from class files and that metap would transform the output to the protobuf format … as I'm writing it I realize something is fishy since the semanticdb already is in the protobuf format … 
Is there a list of executables in the scalameta project and a description of what they do ?

**Comment by xeno-by** [comment] 2018-05-28 16:09
Duplicate of https://github.com/scalameta/scalameta/issues/1541.

**Closed** 2018-05-28 16:10 UTC
Labels: Scalacp
