### ISSUE TITLE
UnreachableError when parsing a pattern bind to a case object

### ISSUE THREAD

**Issue by hugo-vrijswijk** [scalameta/scalameta#2447] opened 2021-08-10 15:28 UTC
The following code throws an `UnreachableError`

```scala
import scala.meta._

q"{ case x @ Y => x }".syntax
```

[Scastie here](https://scastie.scala-lang.org/xKpv6hjQTkSH7AvF2SfjkA)

Lower-casing the pattern bind doesn't cause an exception, and also parses to a different tree:

`{ case x @ Y => x }` becomes:

```
Term.PartialFunction(List(Case(Pat.Bind(Pat.Var(Term.Name("x")), Term.Name("Y")), None, Term.Name("x"))))
```

While `{ case x @ y => x }` becomes:

```
Term.PartialFunction(List(Case(Pat.Bind(Pat.Var(Term.Name("x")), Pat.Var(Term.Name("y"))), None, Term.Name("x"))))
```

Full stacktrace:

```
org.scalameta.UnreachableError: this code path should've been unreachable
	at org.scalameta.UnreachableError$.raise(package.scala:40)
	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.isAmbiguousWithPatVarTerm$1(TreeSyntax.scala:252)
	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.isAmbiguousInParent$1(TreeSyntax.scala:288)
	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.$anonfun$guessIsBackquoted$7(TreeSyntax.scala:295)
	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.$anonfun$guessIsBackquoted$7$adapted(TreeSyntax.scala:295)
	at scala.Option.exists(Option.scala:376)
	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.guessIsBackquoted(TreeSyntax.scala:295)
	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.$anonfun$syntaxTree$1(TreeSyntax.scala:351)
	at scala.meta.prettyprinters.Syntax$$anon$1.apply(Syntax.scala:9)
	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.p(TreeSyntax.scala:126)
	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.$anonfun$syntaxTree$1(TreeSyntax.scala:787)
	at scala.meta.prettyprinters.Syntax$$anon$1.apply(Syntax.scala:9)
	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.p(TreeSyntax.scala:126)
	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.$anonfun$syntaxTree$1(TreeSyntax.scala:1171)
	at scala.meta.prettyprinters.Syntax$$anon$1.apply(Syntax.scala:9)
	at scala.meta.prettyprinters.Show$.indent(Show.scala:72)
	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.$anonfun$syntaxTree$34(TreeSyntax.scala:621)
	at scala.collection.immutable.List.map(List.scala:293)
	at scala.meta.internal.prettyprinters.TreeSyntax$SyntaxInstances.$anonfun$syntaxTree$1(TreeSyntax.scala:621)
	at scala.meta.prettyprinters.Syntax$$anon$1.apply(Syntax.scala:9)
	at scala.meta.internal.prettyprinters.TreeSyntax$.$anonfun$apply$1(TreeSyntax.scala:1284)
	at scala.meta.prettyprinters.Syntax$$anon$1.apply(Syntax.scala:9)
	at scala.meta.prettyprinters.Api$XtensionSyntax.syntax(Api.scala:11)
```

**Comment by hugo-vrijswijk** [comment] 2021-08-10 17:14
I'm willing to take a look at this, but I'm not sure if this is something that should be fixed in the parser, or the printer

**Comment by tgodzik** [comment] 2021-08-10 17:43
Thanks for reporting! 

Does the code compile in Scala 2 actually? If it does, that's most likely something that needs to be fixed in the printer. The code responsible for it resides in TreeSyntax.scala, but I haven't checked exactly what might be going on.

If the code doesn't actually compile we might need to fix in the parser itself and throw an error in that case.

**Comment by hugo-vrijswijk** [comment] 2021-08-10 18:40
Yes, it does compile. For example when pattern matching on a case object and binding with `@`. I've never seen that before today, but it is possible:

```scala
case object Foo

x match {
  case y @ Foo => y
}
```

**Comment by tgodzik** [comment] 2021-08-10 18:42
Then I am pretty sure it's an issue of the missing case in TreeSyntax. It should be possible to just write a test in TermSuite to reproduce it.

**Comment by hugo-vrijswijk** [comment] 2021-08-10 18:49
Would you expect the same parsing as with lowercase variables? So to ` Pat.Var(Term.Name("Y"))` instead of ` Term.Name("Y")` as it does now?

**Comment by tgodzik** [comment] 2021-08-11 10:47
It's parsed like that intentionally since the uppercase are not pattern variables, but they come from outside the pattern match.

**Closed** 2021-08-11 16:32 UTC
