### ISSUE TITLE
missing semanticdb-scalac_2.12.5

### ISSUE THREAD

**Issue by hepin1989** [scalameta/scalameta#1467] opened 2018-04-01 17:12 UTC
```
Downloaded https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.5/scala-compiler-2.12.5-sources.jar
[error] coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     org.scalameta:semanticdb-scalac_2.12.5:2.1.7:
[error]         not found:
[error]             /Users/kerr/.ivy2/local/org.scalameta/semanticdb-scalac_2.12.5/2.1.7/ivys/ivy.xml
[error]             https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.5/2.1.7/semanticdb-scalac_2.12.5-2.1.7.pom
[error]             https://dl.bintray.com/akka/maven/org/scalameta/semanticdb-scalac_2.12.5/2.1.7/semanticdb-scalac_2.12.5-2.1.7.pom
[error] coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     org.scalameta:semanticdb-scalac_2.12.5:2.1.7:
[error]         not found:
[error]             /Users/kerr/.ivy2/local/org.scalameta/semanticdb-scalac_2.12.5/2.1.7/ivys/ivy.xml
[error]             https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.5/2.1.7/semanticdb-scalac_2.12.5-2.1.7.pom
[error]             https://dl.bintray.com/akka/maven/org/scalameta/semanticdb-scalac_2.12.5/2.1.7/semanticdb-scalac_2.12.5-2.1.7.pom
[error] (coursierResolutions) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     org.scalameta:semanticdb-scalac_2.12.5:2.1.7:
[error]         not found:
[error]             /Users/kerr/.ivy2/local/org.scalameta/semanticdb-scalac_2.12.5/2.1.7/ivys/ivy.xml
[error]             https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.5/2.1.7/semanticdb-scalac_2.12.5-2.1.7.pom
[error]             https://dl.bintray.com/akka/maven/org/scalameta/semanticdb-scalac_2.12.5/2.1.7/semanticdb-scalac_2.12.5-2.1.7.pom
[error] (ssExtractDependencies) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     org.scalameta:semanticdb-scalac_2.12.5:2.1.7:
[error]         not found:
[error]             /Users/kerr/.ivy2/local/org.scalameta/semanticdb-scalac_2.12.5/2.1.7/ivys/ivy.xml
[error]             https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.12.5/2.1.7/semanticdb-scalac_2.12.5-2.1.7.pom
[error]             https://dl.bintray.com/akka/maven/org/scalameta/semanticdb-scalac_2.12.5/2.1.7/semanticdb-scalac_2.12.5-2.1.7.pom
[error] Total time: 52 s, completed 2018-4-2 1:09:29
```

**Comment by olafurpg** [comment] 2018-04-01 18:30
Duplicate of #1445. There won't be a 2.12.5 release due to the regressions. We'll release for 2.12.6 once it's out!

**Closed by olafurpg** 2018-04-01 18:30 UTC
