### ISSUE TITLE
Exception on calling .parse[Source]

### ISSUE THREAD

**Issue by johannegger** [scalameta/scalameta#443] opened 2016-06-27 07:54 UTC
We ran into an exception when calling `.parse[Source]` on a `java.nio.File`. Probably this should not happen since .parse returns a `Parsed` and one therefore doesn't expect the code to throw exceptions.

```
org.scalameta.invariants.InvariantFailedException: invariant failed:
when verifying ScalametaTokenizer.this.input.chars.apply(curr.endOffset.+(1)).==('\"')
found that ScalametaTokenizer.this.input.chars.apply(curr.endOffset.+(1)) is not equal to '\"'
where ScalametaTokenizer = scala.meta.internal.tokenizers.ScalametaTokenizer@334ebcaa
    at org.scalameta.invariants.InvariantFailedException$.raise(Exceptions.scala:15)
    at scala.meta.internal.tokenizers.ScalametaTokenizer.emitContents$1(ScalametaTokenizer.scala:222)
    at scala.meta.internal.tokenizers.ScalametaTokenizer.loop$1(ScalametaTokenizer.scala:231)
    at scala.meta.internal.tokenizers.ScalametaTokenizer.uncachedTokenize(ScalametaTokenizer.scala:246)
    at scala.meta.internal.tokenizers.ScalametaTokenizer.tokenize(ScalametaTokenizer.scala:34)
    at scala.meta.internal.tokenizers.ScalametaTokenizer$$anon$2.apply(ScalametaTokenizer.scala:262)
    at scala.meta.tokenizers.Api$XtensionTokenizeDialectInput.tokenize(Api.scala:23)
    at scala.meta.tokenizers.Api$XtensionTokenizeInputLike.tokenize(Api.scala:12)
    at scala.meta.internal.parsers.ScalametaParser.scannerTokens$lzycompute(ScalametaParser.scala:204)
    at scala.meta.internal.parsers.ScalametaParser.scannerTokens(ScalametaParser.scala:204)
    at scala.meta.internal.parsers.ScalametaParser.<init>(ScalametaParser.scala:165)
    at scala.meta.internal.parsers.ScalametaParser$$anon$190.apply(ScalametaParser.scala:3596)
    at scala.meta.parsers.Api$XtensionParseDialectInput.parse(Api.scala:21)
    at scala.meta.parsers.Api$XtensionParseInputLike.parse(Api.scala:10)
```

**Comment by xeno-by** [comment] 2016-06-27 12:23
This shouldn't be. How do you invoke parse? Could you show the full stack trace?

**Comment by johannegger** [comment] 2016-07-01 15:16
the invocation of parse is [here](https://github.com/codacy/codacy-scalameta/blob/3a3bd7ff3278e5b3bbc3324bf39827e94f9196d3/src/main/scala/codacy/CodacyScalameta.scala#L64) - it's called on a java.nio.file.File
Now it is protected with a Try but that was just introduced to fix the issue. 

I will try to get my hands on the full stack trace but it might be difficult - we just saw it once in the logs of a production server.

**Comment by xeno-by** [comment] 2017-03-03 14:00
@johannegger Could you provide a problematic file?

**Comment by piton4k** [comment] 2017-06-26 15:59
Hi I'm getting the same error, and have been for a while, until I decided to investigate a bit.
Apparently it's caused by any interpolated string (at least any I tried) immediately followed by newline, guess what, with CRLF line end encoding (yay Windows).

Just try this one with CRLF:
```scala
object InterpolationError {
  val parse = s"nope"
}
```

I guess one of those ±1 is not working well with 2 `Char`s for line end.

Inserting other whitespace characters or line comment after the interpolated string worked to avoid the exception. Or setting the line ends to LF (I know the technology is not there yet), which is a bit difficult on Windows.

**Comment by olafurpg** [comment] 2017-06-27 12:13
A quick grep in the parser shows we test against \n in several places

```
$ rg "\[LF\]"
scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala
257:          if (scannerTokens(i).is[LF] || scannerTokens(i).is[FF]) {
636:      token.is[LF] || token.is[LFLF] || token.is[EOF]
654:      token.is[Semicolon] || token.is[LF] || token.is[LFLF] || token.is[EOF]
697:      token.is[LF] || token.is[LFLF] || token.is[CR]
1535:    if (token.is[LF]) next()
1539:    if (token.is[LF] || token.is[LFLF])
1545:    if (token.is[LF] && ahead { token.is[T] }) newLineOpt()
1550:    if (token.is[LF] && ahead { p(token) }) newLineOpt()
```

Changing those to `.is[Newline]` where Newline is a `@classifier` like [here](https://github.com/scalameta/scalameta/blob/d0804413ab1845fc9603ef73282bed1c0616970d/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L652) that handles CRLF and LF would probably go a long way to fix these issues. We recently enabled Appveyor CI so we can catch regressions/issues on Windows. Note that we only enable a subset of tests in appveyor.yml, please update it if you add new tests. Would someone with a Windows computer be interested in contributing a fix for this?

**Comment by olafurpg** [comment] 2017-07-12 15:01
I spent some time trying to track down this issue in https://github.com/olafurpg/scalameta/commit/42591c11430cb63b9cadcbb36ba08079440efd92
The problem appears to be the offsets emitted by LegacyScanner and not in ScalametaParser or ScalametaTokenizer. I don't have more time to investigate right now so I propose we leave this for milestone to not block the upcoming v2 release.

**Comment by olafurpg** [comment] 2017-07-12 15:02
The workaround for users affected by this issue is to convert CRLF to LF before running the parser.

**Comment by tgodzik** [comment] 2021-05-11 10:32
I can no longer reproduce it on Windows.

**Closed by tgodzik** 2021-05-11 10:32 UTC
Labels: Parsing
