### ISSUE TITLE
Scalahost does not work on Windows

### ISSUE THREAD

**Issue by a-nigredo** [scalameta/scalameta#935] opened 2017-06-11 11:02 UTC
Scalahost does not save semanticdb because of an error on windows:

`java.net.URISyntaxException: Illegal character in opaque part at index` 

The problem is in usage of file path value in scala.meta.io.AbsolutePath#toNio. 
Since windows builds path like "C:\myProject\target" it can't pass validation in URI class.

How to reproduce:

1. Create sbt project with scalameta and scalahost.
2. Run sbt clean compile

**Comment by xeno-by** [comment] 2017-06-11 19:59
@olafurpg How do we improve our CI to also check Windows?

**Comment by DavidDudson** [comment] 2017-06-11 20:01
@xeno-by appveyor is the only decent way IMO. It's pretty easy to setup and free for OSS

**Comment by a-nigredo** [comment] 2017-06-12 07:17
@xeno-by @olafurpg @DavidDudson I guess we have to replace backslashes with slashes if it is windows and just add test for it then we don't need CI for windows

**Comment by xeno-by** [comment] 2017-06-12 17:19
Well, who knows what other Windows issues we have / regressions we introduce. I think it would be beneficial to have a Windows CI. @olafurpg what do you think about appveyor?

**Comment by olafurpg** [comment] 2017-06-13 07:31
I agree it would be nice to run or CI on Appveyor, but does require work and discipline to keep green. If we enable it, we have to be strict that we can't merge PRs unless they are green on Appveyor. My experience is that failing tests on Appveyor are more often caused by configuration issues or resolution errors rather than Windows specific bugs. When it is a Windows specific bug, it's hard/slow to reproduce or iterate on a solution because I don't have a Windows machine locally.

**Comment by olafurpg** [comment] 2017-06-19 09:26
I was able to reproduce this error on Appveyor in https://github.com/scalameta/scalameta/pull/951 My aversion to appveyor was largely caused by a bad prior experience trying to configure a cached installation of sbt. I gave it another shot this weekend in https://github.com/scalameta/scalafmt/pull/986 using scoop and that seems to work OK, completing the unit tests in ~3 minutes. I think we should try to enable appveyor in our CI pipeline to prevent further windows related issues.

**Comment by olafurpg** [comment] 2017-06-19 10:10
@a-nigredo  https://github.com/scalameta/scalameta/commit/c4ebc773f0796281171f55bccd4455917e9e0876 replaces `Paths.get(file.toURI)` with `file.toPath`, which should fix the issue reported here. I'm testing the fix in #953

**Comment by olafurpg** [comment] 2017-06-19 10:16
Shoot, it seems out build exceeds the 1000mb cache limit on appveyor https://ci.appveyor.com/project/olafurpg/scalameta/build/6#L2114 I'm surprised since the log shows we only upload ~210mb

```
Cache 'C:\Users\appveyor\.ivy2' - Uploading (49,536,474 bytes)...100%Error uploading cache entry to the cache storage: The maximum cache size of 1,000 MB will be exceeded.
Cache 'C:\Users\appveyor\.coursier' - Uploading (108,537,377 bytes)...100%Error uploading cache entry to the cache storage: The maximum cache size of 1,000 MB will be exceeded.
Cache 'C:\Users\appveyor\scoop\cache' - Uploading (60,325,092 bytes)...100%
```

Has anyone experienced this with Appveyor before?

**Comment by olafurpg** [comment] 2017-06-19 10:38
It appears that each entry is not allowed to exceed 100mb, https://www.appveyor.com/docs/build-cache/#saveupdate-cache-before-build-finishes I bumped up the compression flags in https://github.com/scalameta/scalameta/pull/953/commits/e36c3f9ed27858d820471b8d323624b7154d3ea5, but I suspect that will not be enough :/

**Comment by xeno-by** [comment] 2017-06-26 23:57
@olafurpg Is this fixed now?

**Comment by olafurpg** [comment] 2017-06-27 06:47
Yes, this should be fixed. In addition, we now run CI on appveyor testing the full pipeline works on Windows for every PR.

**Comment by olafurpg** [comment] 2017-06-27 06:48
Forgot to link, here is the PR that fixed the issue https://github.com/scalameta/scalameta/pull/953

**Closed by olafurpg** 2017-06-27 06:47 UTC
Labels: Semantic
