### ISSUE TITLE
get the name of anonymous class by parsing .scala file

### ISSUE THREAD

**Issue by Charmik** [scalameta/scalameta#1857] opened 2019-04-23 10:28 UTC
Hello! I want to get the name of the class where is this variable. Simple example:
`class ScalaTest {
  new Thread {
    override def run {
      val t = "T1"
    }
  }
}`
for variables not in anonymous classes it's easy, I am looking for Defn.Val in tree and then I go to parent's, and if it's Defn.Object || Defn.Class || Defn.Trait I just take .name.value on it. That's how I get class name where is this variable. 
For anonymous classes I find variables are the same, but when I go to parent's I don't know how to get the name of anonymous class (I want to get "ScalaTest$$anon$1" how it compiles by scalac). 
But if I go to parent's I get:
Template$TemplateImpl
Term$NewAnonymous$TermNewAnonymousImpl (seems like what I need, but I didn't get how can I get the name of the class)
Template$TemplateImpl
Defn$Class$DefnClassImpl

and if I get .structure of the class I get:
Defn.Class(Nil, Type.Name("ScalaTest"), Nil, Ctor.Primary(Nil, Name(""), Nil), Template(Nil, Nil, Self(Name(""), None), List(Term.NewAnonymous(Template(Nil, List(Init(Type.Name("Thread"), Name(""), Nil)), Self(Name(""), None), List(Defn.Def(List(Mod.Override()), Term.Name("run"), Nil, Nil, Some(Type.Name("Unit")), Term.Block(List(Defn.Val(Nil, List(Pat.Var(Term.Name("t"))), None, Lit.String("T1")))))))))))

where I don't have the name of the class too. So how can I get it? Thanks!

**Comment by olafurpg** [comment] 2019-04-23 10:33
Thank you for reporting! Can you elaborate on the exact problem? You can btw match against `case m: Member => m.name.value` to handle class/trait/object.

This doesn't sounds like a bug, you might want to try asking on Gitter instead.

**Comment by olafurpg** [comment] 2019-04-23 10:50
I see you asked on Gitter, closing this since it's a question and not a bug report.

**Closed by olafurpg** 2019-04-23 10:50 UTC
