### ISSUE TITLE
Extracting Term.Name from Param.Name gives type error

### ISSUE THREAD

**Issue by ValentinRutz** [scalameta/scalameta#278] opened 2015-10-20 13:11 UTC
Trying to extract Term.Name from Term.Param.Name gives type error:

type mismatch when unquoting;
 found   : scala.meta.Tree
 required: scala.meta.Term.Name
                case q"${paramName: Term.Name}" => Local(paramName)

**Comment by xeno-by** [comment] 2015-10-20 13:42
Duplicate of https://github.com/scalameta/scalameta/issues/275

**Closed by xeno-by** 2015-10-20 13:42 UTC
