### ISSUE TITLE
No Symbols for `Ctor.Ref.Name`

### ISSUE THREAD

**Issue by stuhood** [scalameta/scalameta#806] opened 2017-04-20 06:05 UTC
For scalahost `1.8.0-520-f6d600cd.1492126021620` and code like:
```
package com.example

class Printer {
  def print(msg: String): Unit =
    println(msg)
}

object Example {
  def main(args: Array[String]): Unit = {
    val msg = "Hello World"
    // Comment.
    new Printer().print(msg)
  }
}
```
...the `Ctor.Ref.Name` representing the constructor call does not have a symbol attached, and throws (verbatim):
```
Exception in thread "main" error: fatal error: semantic DB doesn't contain 
This is a bug; please report it via https://github.com/scalameta/scalameta/issues/new
```

**Comment by stuhood** [comment] 2017-04-20 06:44
Whoops! False alarm. It looks like this was the constructor definition instead... ie:
```
scala.meta.Ctor$Primary$CtorPrimaryImpl
  scala.meta.Ctor$Ref$Name$CtorRefNameImpl
```

**Comment by stuhood** [comment] 2017-04-20 06:57
I think I remain confused as to how to get the proper Symbol for a constructor though... the Symbol for a `Ctor.Ref.Name` at a callsite seems to be the Symbol for the constructor's class, rather than the constructor itself.

**Comment by xeno-by** [comment] 2017-04-30 05:15
Looks like a duplicate of https://github.com/scalameta/scalameta/issues/655

**Closed by xeno-by** 2017-04-30 05:15 UTC
Labels: Semantic
