### ISSUE TITLE
Problem with quasiquote for "Constructor - Applied Reference" 

### ISSUE THREAD

**Issue by johannegger** [scalameta/scalameta#310] opened 2015-11-11 09:43 UTC
the quasiquote ```ctor"$ctorref(...$aexprssnel)"``` defines aexprssnel with 3 '.' but it seems to work only with 2. to me the issue looks very similar to the problem described in:
https://github.com/scalameta/scalameta/issues/301

**Comment by xeno-by** [comment] 2016-05-26 13:53
Duplicate of #277

**Closed by xeno-by** 2016-05-26 13:53 UTC
Labels: Quasiquotes
