### ISSUE TITLE
Parsing fails on SIP-64 changes

### ISSUE THREAD

**Issue by asarkar** [scalameta/scalameta#4090] opened 2024-12-21 12:41 UTC
[SIP-64](https://docs3.scala-lang.org/sips/sips/typeclasses-syntax.html) changes context bound and given clause syntaxes. It has been committed to Scala 3 codebase by the commit [14acdc0](https://github.com/scala/scala3/commit/14acdc06067a202f381fa9066a961cebb1314d6a).
```scala
trait Display[A]:
  def display(value: A): String

final case class Cat(name: String, age: Int, color: String)
  
 given catDisplay: Display[Cat]:
    def display(cat: Cat): String =
      s"${cat.name} is a ${cat.age} year-old ${cat.color} cat."
```

Note the `given` definition ends with `:`, not `with`, as the latter has been deprecated and emits a warning:
> Given member definitions starting with with are no longer supported; use {...} or : followed by newline instead

Using scalafmt 3.8.3 (even the latest v3.8.4-RC3), this fails.
```
[6] error: /path/to/Cat.scala: org.scalafmt.dynamic.exceptions.PositionExceptionImpl: /path/to/Cat.scala:6: error: [dialect scala3] `;` expected but `:` found
[6]   given catDisplay: Display[Cat]:
[6]                                 ^
[6] Caused by: /path/to/Cat.scala:6: error: [dialect scala3] `;` expected but `:` found
[6]   given catDisplay: Display[Cat]:
[6]                                 ^
[6] 	at org.scalafmt.Scalafmt$.$anonfun$doFormatOne$2(Scalafmt.scala:111)
[6] 	at scala.meta.parsers.Parsed.fold(Errors.scala:12)
[6] 	at scala.meta.parsers.Parsed.fold$(Errors.scala:10)
[6] 	at scala.meta.parsers.Parsed$Error.fold(Errors.scala:28)
[6] 	at org.scalafmt.Scalafmt$.doFormatOne(Scalafmt.scala:114)
[6] 	at org.scalafmt.Scalafmt$.doFormat(Scalafmt.scala:90)
[6] 	at org.scalafmt.Scalafmt$.$anonfun$formatCode$3(Scalafmt.scala:78)
```

**Comment by kitbellew** [comment] 2024-12-21 15:57
duplicate of #4047.

**Closed** 2024-12-22 22:08 UTC
