### ISSUE TITLE
Possibility to generate comments with quasiquotes

### ISSUE THREAD

**Issue by mikaelstaldal** [scalameta/scalameta#1137] opened 2017-10-20 07:42 UTC
I use Scalameta to generate Scala source code from scratch, using quasiquotes heavily.

It would be useful to be able to insert comments, and in particular ScalaDoc comments, into the generated source.

**Comment by olafurpg** [comment] 2017-10-20 08:45
I believe @jvican did some work in this space a while back, but it was quite tricky to implement iirc. Maybe it's possible to add new tree nodes in like `Comment.{Docstring,Multiline,LeadingInline, TrailingInline}` that TreeSyntax respects. Are you interested in contributing @mikaelstaldal ?

A workaround for now is to add the comments after calling `.syntax`.

```scala
@ val classes = List("A", "B").map { name =>
  q"class ${Type.Name(name)} extends Foo"
  }.map { cls =>
   "/** comment */\n" + cls.syntax
  }.mkString("\n\n")
classes: String = """/** comment */
class A extends Foo

/** comment */
class B extends Foo"""
```

**Comment by mikaelstaldal** [comment] 2017-10-21 14:23
This workaround is quite impractical for me since I want Scaladoc comments on methods as well. 

My use case is to generate Scala code from a data structure definition with another syntax (like [Avro](http://avro.apache.org/docs/current/spec.html#schemas) or [Protobuf](https://developers.google.com/protocol-buffers/docs/reference/proto3-spec)).

**Comment by olafurpg** [comment] 2017-10-21 19:42
I agree the current state for code generation is pretty bad, when scalameta should on paper be amazing for code generation! TL;DR, if you are looking for a quick-fix I suggest you use an alternative library like maybe https://github.com/typelevel/paiges/ to print the code. If you want to use scalameta+quasiquotes for code generation, read on 😄 

I have been working on a rewrite of the pretty-printer for the past few weeks, with the aim to

- fix tons of bugs in the current pretty printer (see https://github.com/scalameta/scalameta/issues/567)
- smart line wrap for large expressions
- print comments :)

The project is here https://github.com/olafurpg/scala-syntax I'm still at the "fix tons of bugs" phase (almost done!) and haven't gotten around to comments yet. I took a quick stab at adding custom tree nodes for docstrings but seems to be a dead end, details here https://github.com/olafurpg/scala-syntax/commit/d5ddc6c32c4fb6226a81c035d572fd9a37a0b1f6

This problem can be summarized into the following fundamental question: how do we attach comments to custom tree nodes like `Term.Name("a")`? If we solve that, we can make quasiquotes use that same system.

One potential solution is to use "attachments" (somewhat similar to what's done in the Scala compiler). A low-level api prototype could look something like

```scala
case class Docstring(comment: String)
val attachments = new Attachments
val method = q"def foo = 2"
val cls = q"class Foo { $method; def bar = 3 }"
val source = source"""
package a.b
import b.c
$cls
"""
val attachments = Attachments
  .attachDocstring(method, "Returns 2")
  .attachTrailingComment(method, "FIXME")
  .attachDocstring(cls, "Foo has two methods foo and bar.")
attachments.print(source)
// prints
package a.b

import b.c

/** Foo has two methods foo and bar */
class Foo {
  /** Returns 2 */
  def foo = 2 // FIXME
  def bar = 3
}
```

The public API can of course be much nicer, but the underlying data model would be something like that. Any thoughts? @xeno-by @andyscott

**Comment by olafurpg** [comment] 2017-10-21 21:52
Great news, I believe I made some really nice progress in this front! I got the following test suite passing 👏 

```scala
val foo = q"def foo = 2".withLeadingComment("/** Returns 2 */\n")
val bar = q"def bar = 3".withTrailingComment(" // FIXME")
val qux = q"def qux = 4".withLeadingComment(
  """/**
    |  * Example multiline docstring
    |  *
    |  * @param a The "a"
    |  */
    |""".stripMargin
)
val zzz = q"def zzz = 5"
  .withLeadingComment("// Comment 2\n") // Note: reverse order, unintuitive?
  .withLeadingComment("// Comment 1\n")
val Foo = q"class Foo { $foo; $bar; $qux; $zzz }"
  .withLeadingComment("/** Foo is great */\n")
val source = source"""
package a.b
import b.c
$Foo
"""
val obtained = TreePrinter.print(source).render(100)
// Note that indentation is corrected :D
val expected =
  """
package a.b
import b.c

/** Foo is great */
class Foo {
  /** Returns 2 */
  def foo = 2

  def bar = 3 // FIXME

  /**
    * Example multiline docstring
    *
    * @param a The "a"
    */
  def qux = 4

  // Comment 1
  // Comment 2
  def zzz = 5
}
"""
assertNoDiff(obtained, expected)
```

Implementation in https://github.com/olafurpg/scala-syntax/compare/docstrings?expand=1

You can give it a try @mikaelstaldal by depending on the library by source

```scala
// build.sbt
lazy val Format = RootProject(
  uri(
    "git://github.com/olafurpg/scala-syntax.git#b01009c703427498705e0e5e4fbf938cb262dcd2"
  )
)
lazy val format = ProjectRef(Format.build, "format")

// Codegen.scala
import org.scalafmt.internal.TreePrinter
val codegen = q"..." // 
TreePrinter.print(codegen).render(100): String
```

**Comment by mikaelstaldal** [comment] 2017-10-23 09:29
This is not really what I am looking for. It will make the code of my code generator quite messy. I would like to simply be able to include the comments in the quasiquote to have a consistent template for the generated code.

**Comment by olafurpg** [comment] 2017-10-23 09:43
Sorry that's the best I got for you. It's probably possible to integrate
that API with quasi quotes but I'm I probably won't have time to look into
it.

**Comment by mikaelstaldal** [comment] 2017-10-23 16:24
Then Scalameta is probably not what I need for code generation.

**Comment by olafurpg** [comment] 2017-10-30 13:41
Duplicate of https://github.com/scalameta/scalameta/issues/379#issuecomment-327342191

**Closed by olafurpg** 2017-10-30 13:41 UTC
