### ISSUE TITLE
Parsing a file that has string interpolation causes InvariantFailedException

### ISSUE THREAD

**Issue by hugo-vrijswijk** [scalameta/scalameta#1597] opened 2018-06-08 15:14 UTC
I have a file with the following content: 
```scala
package helloWorld

object Greeter {
  def sayHello(name: String) = s"Hello, $name"
}
```

Callling `file.parse[Source]` causes the following exception: 
```
org.scalameta.invariants.InvariantFailedException: invariant failed:
when verifying ScalametaTokenizer.this.input.chars.apply(curr.endOffset.+(1)).==('\"')
found that ScalametaTokenizer.this.input.chars.apply(curr.endOffset.+(1)) is not equal to '\"'
where ScalametaTokenizer = scala.meta.internal.tokenizers.ScalametaTokenizer@117e2797
	at org.scalameta.invariants.InvariantFailedException$.raise(scalameta.sc:11)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.emitContents$1(scalameta.sc:218)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.loop$1(scalameta.sc:227)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.uncachedTokenize(scalameta.sc:272)
	at scala.meta.internal.tokenizers.ScalametaTokenizer.tokenize(scalameta.sc:27)
	at scala.meta.internal.tokenizers.ScalametaTokenizer$$anon$2.apply(scalameta.sc:283)
	at scala.meta.tokenizers.Api$XtensionTokenizeDialectInput.tokenize(scalameta.sc:17)
	at scala.meta.tokenizers.Api$XtensionTokenizeInputLike.tokenize(scalameta.sc:6)
	at scala.meta.internal.parsers.ScalametaParser.scannerTokens$lzycompute(scalameta.sc:179)
	at scala.meta.internal.parsers.ScalametaParser.scannerTokens(scalameta.sc:179)
	at scala.meta.internal.parsers.ScalametaParser.<init>(scalameta.sc:136)
	at scala.meta.internal.parsers.ScalametaParser$$anon$189.apply(scalameta.sc:3441)
	at scala.meta.parsers.Api$XtensionParseDialectInput.parse(scalameta.sc:17)
	at scala.meta.parsers.Api$XtensionParseInputLike.parse(scalameta.sc:6)
```

Putting the content in a string and then parsing it works fine. Putting the interpolated string in { } brackets also doesn't cause an exception. 
As I am parsing files that I don't have control over, this is blocking for me unless there's a workaround (or I'm doing something wrong).

Tried on Scalameta version 3.3.1 and 4.0.0-M2
Scala version 2.12.6
Environment: Windows

**Comment by olafurpg** [comment] 2018-06-08 20:11
Thanks for reporting! This error message looks familiar, seems like a duplicate of https://github.com/scalameta/scalameta/issues/1177. What happens if you `.replace("\r\n", "\n")` before parsing?

**Comment by hugo-vrijswijk** [comment] 2018-06-11 09:52
Yeah, that does seem to fix it. Still, it seems like something Scalameta should be able to handle. Or at the very least provide a better exception message. Is fixing this on the planning? If not, I wouldn't mind taking a look at it if you could point me in the right direction

**Comment by olafurpg** [comment] 2018-06-11 10:01
Good to know there is a workaround. This is absolutely a bug that should be fixed, I would love your help if you are interested in taking a stab at this :) 

A good place to start would be to reproduce the bug in `TokenizerSuite` https://github.com/scalameta/scalameta/blob/6a0d5a289db8fea4fd38a2a3e60a61b0f86f8b14/tests/shared/src/test/scala/scala/meta/tests/tokenizers/TokenizerSuite.scala#L854-L857

Beware, the tokenizer code is quite hairy, especially around interpolators. The fix will likely either touch `LegacyScanner` (which is an adapted version of the scalac scanner) https://github.com/scalameta/scalameta/blob/6a0d5a289db8fea4fd38a2a3e60a61b0f86f8b14/scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/LegacyScanner.scala or `ScalametaTokenizer` (converts scalac TokenData into high-level `scala.meta.Token`) https://github.com/scalameta/scalameta/blob/6a0d5a289db8fea4fd38a2a3e60a61b0f86f8b14/scalameta/tokenizers/shared/src/main/scala/scala/meta/internal/tokenizers/ScalametaTokenizer.scala

Let me know if you have any questions!

I'll close this ticket as a duplicate of #1177

**Closed by olafurpg** 2018-06-11 10:01 UTC
