### ISSUE TITLE
Alternative parser technology

### ISSUE THREAD

**Issue by MasseGuillaume** [scalameta/scalameta#62] opened 2014-11-25 00:34 UTC
Hum the parser code is quite impressively long why it's not using something like parboiled2 ?

https://github.com/sirthias/parboiled2

**Comment by xeno-by** [comment] 2015-06-06 17:16
We are very excited to witness rapid development of fastparse (https://github.com/lihaoyi/fastparse), and it would be really interesting to have a fastparse-based parser that emits scala.meta trees with filled in tokens.

In the near future, I'll be addressing https://github.com/scalameta/scalameta/issues/150 and https://github.com/scalameta/scalameta/issues/154, which should make this issue approachable for contributions.

**Comment by sirinath** [comment] 2015-06-15 16:10
Maybe this is also a good contender to be included: https://github.com/begeric/FastParsers

**Comment by densh** [comment] 2015-06-15 16:15
@sirinath This ticket is not just about picking a parser combinator library, there are also has to be an implementation of full-blown parser for Scala grammar including all of its quirks.

**Comment by sirinath** [comment] 2015-06-15 16:25
For some one who attempts this the above might help the cause as it claims to have a similar interface as the Scala parse combinators.

**Comment by lihaoyi** [comment] 2015-07-01 02:25
> My 2c is a "me too" to what @paulp said: the hard part about parsers is not parsing correct code (and relatively simple code, like scala/scala), but having clear (and well positioned) error messages

https://github.com/lihaoyi/fastparse/blob/master/scalaparse/shared/src/test/scala/scalaparse/unit/FailureTests.scala

@dragos I don't know what it'd take for you to be proven wrong, but IMHO this basically trumps Scalac's error messages in terms of correctness of parser: it shows all options that can make progress at the point of failure, with exact error positions. 

Furthermore, apart from having a nice toString, the failure is actually a *data structure*. This means it's trivial to programmatically/interactively expand e.g. 

```scala
SmallerExprOrLambda -> ParenedLambda | PostfixLambda

LocalMod            -> `abstract` | `final` | `sealed` | `implicit` | `lazy

BindPattern         -> Binding ~ InfixPattern | InfixPattern | VarId
```

and so on recursively as deeply as you would like. These aren't strings anymore.

--------------

Furthermore, because these aren't strings, you can easily tag parts of the grammar with identity extra-metadata-parsers such that if the failure trace contains these parsers, the metadata will be present in the stack trace and can be used e.g. for a custom explanation. This would be as simple as replacing 

```scala
val ObjDef = P(...)
```

with

```scala
val ObjDef = P(...)(FuncName("ObjDef", "The definition of a Scala `object` or singleton")
```

A similar technique can be used to tag arbitrary sub-sections of parsers such that their failure results in custom error messages, e.g. making procedure-syntax contain a custom error that can be extracted to show the user would be as simple as swapping

```scala
`=`          -> `=`.failureMsg("Procedure syntax has been remove since 2.11.x, please us `def f: Unit = ...` if you want a function returning `Unit`")
``` 

And then extracting the message from the `Failure` object via

```scala
failure.traced.fullStack.collectFirst{case Tagged(_, msg) => msg }
```

----------

Lastly, this has no dependencies, and parses at 40,000LOC/s, ~10x slower than Scalac's own parser

Is there anything else you'd from this? ^_^

**Comment by xeno-by** [comment] 2016-05-06 15:28
Starting from 0.1.0-RC5, scala.meta's infrastructure no longer requires Tree.tokens to be assigned for every parsed AST. Now the only thing that the parser is expected to do is to assign Tree.origin, which is equivalent to providing a position, i.e. a start-point-end range. Our tokenizer is then able to calculate tokens on its own based on the provided position.

I hope that this will remove unnecessary barriers to providing an alternative parser for scala.meta trees.

The only additional complication that I can think of at the moment is the necessity to support the Quasiquote dialect of Scala, i.e. being able to accept stuff like `..$xs` or `foo(...$argss)` and to transform it  to a scala.meta AST enriched by nodes representing ellipses and unquotes.

/cc @lihaoyi

**Comment by xeno-by** [comment] 2017-07-05 23:57
Our parser has been serving us well for 3+ years, which shows that we're not in the market for alternative parser technologies. Therefore I'm closing this issue, and if something groundbreaking comes up, we can always reopen it.

**Closed by xeno-by** 2017-07-05 23:57 UTC
Labels: Parsing
