### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by ratoshniuk** [scalameta/scalameta#1831] opened 2019-02-03 07:32 UTC
Hello everyone! I recently start using vsc with metals and found that it currently does not support code completion and doesn't expand list of properties and methods after putting a dot. What is a current progress of this issue? And maybe there some workarounds for current usage (maybe other plugins)

Thank you!

**Comment by olafurpg** [comment] 2019-02-03 07:47
Thanks for reporting! This is a duplicate of https://github.com/scalameta/metals-feature-requests/issues/8 There is no workaround for current usage.

**Closed by olafurpg** 2019-02-03 07:47 UTC
