### ISSUE TITLE
use MiMa to ensure binary compatibility

### ISSUE THREAD

**Issue by xeno-by** [scalameta/scalameta#386] opened 2016-05-08 14:42 UTC
We should have an automatic way to avoid accidental breakages of compatibility when we release our first stable version.

**Comment by xeno-by** [comment] 2016-05-29 08:28
Strictly speaking, this is unnecessary for the 1.0.0 itself. Mima will become mandatory only for subsequent releases.

**Comment by olafurpg** [comment] 2017-07-06 10:18
Duplicate of #844

**Closed by olafurpg** 2017-07-06 10:18 UTC
Labels: Build
