### ISSUE TITLE
substituting blocks doesn't always roundtrip / .toString doesn't always parse as the same structure with blocks

### ISSUE THREAD

**Issue by dlwh** [scalameta/scalameta#2278] opened 2021-04-11 05:53 UTC
In the code snippet below, you'll see that a block following a new... becomes an anonymous class on roundtrip.

```scala
import scala.meta._

val s = source"""
object Foo {
  def foo() = {
    val bar = new String("333")
    qux
  }
}
"""

val transformed = s.transform{
  case Term.Name("qux") =>
    q"{3}"
}

println(transformed)
println(transformed.structure)

val roundtripped = Input.String(transformed.toString).parse[Source].get
println(roundtripped)
println(roundtripped.structure)
```

produces:

```
object Foo {
  def foo() = {
    val bar = new String("333")
    {
      3
    }
  }
}
Source(List(Defn.Object(Nil, Term.Name("Foo"), Template(Nil, Nil, Self(Name(""), None), List(Defn.Def(Nil, Term.Name("foo"), Nil, List(List()), None, Term.Block(List(Defn.Val(Nil, List(Pat.Var(Term.Name("bar"))), None, Term.New(Init(Type.Name("String"), Name(""), List(List(Lit.String("333")))))), Term.Block(List(Lit.Int(3)))))))))))
object Foo {
  def foo() = {
    val bar = new String("333")
    {
      3
    }
  }
}
Source(List(Defn.Object(Nil, Term.Name("Foo"), Template(Nil, Nil, Self(Name(""), None), List(Defn.Def(Nil, Term.Name("foo"), Nil, List(List()), None, Term.Block(List(Defn.Val(Nil, List(Pat.Var(Term.Name("bar"))), None, Term.NewAnonymous(Template(Nil, List(Init(Type.Name("String"), Name(""), List(List(Lit.String("333"))))), Self(Name(""), None), List(Lit.Int(3)))))))))))))

**Comment by dlwh** [comment] 2021-04-11 05:55
actually it's easier than all that:

val s = source"""
object Foo {
  def foo() = {
    val bar = new String("333");
    {3}
  }
}
"""

doesn't roundtrip. No traversal needed.

**Comment by tgodzik** [comment] 2021-04-23 15:43
Thanks for reporting! We could probably fix it by including a newline or `;` when printing a block in https://github.com/scalameta/scalameta/blob/76ec737c8724b15fc5ee18961782ef7d1c2edc71/scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala

We would most likely need to check if the next token (non whitespace or comment) after Term.New belongs to Term.Block and in that case add `;`

**Comment by tgodzik** [comment] 2021-05-05 15:15
This is actually a duplicate of https://github.com/scalameta/scalameta/issues/2046

**Closed by tgodzik** 2021-05-05 15:15 UTC
